"""Rename Access to Permission and update relationships

Revision ID: e2e84149d3b9
Revises: 37c518501056
Create Date: 2025-10-27 20:12:26.723941

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e2e84149d3b9"
down_revision: str | Sequence[str] | None = "37c518501056"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
